AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'bin/**'
    - 'vendor/**/*'
    - 'spec/spec_helper.rb'
    - 'db/migrate/**'
    - 'node_modules/**/*'

MethodLength:
  Max: 300
  Exclude:
    - 'spec/domain/external_services/w_underground/transforms/forecast_ten_days_spec.rb'

Metrics/ClassLength:
  Max: 200

Metrics/LineLength:
  Max: 125
  Exclude:
    - 'config/initializers/devise.rb'

Metrics/AbcSize:
  Max: 21
  Exclude:
    - 'spec/support/weather_watch_test_helper.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/RedundantSelf:
    Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false